ConferenceManagement/Ucoin.Conference.Web/Controllers/ConferenceController.cs
namespace Ucoin.Conference.Web.Controllers
{
    using System;
    using System.Web.Mvc;
    using Ucoin.Conference.Services;

    public class ConferenceController : Controller
    {
        private readonly IConferenceViewService dao;

        public ConferenceController(IConferenceViewService dao)
        {
            this.dao = dao;
        }

        public ActionResult Display(string conferenceCode)
        {
            var conference = this.dao.GetConferenceDetails(conferenceCode);

            // Reply with 404 if not found?
            //if (conference == null)

            return View(conference);
        }
    }
}

ConferenceManagement/Ucoin.Conference.Web/Controllers/DefaultController.cs
namespace Ucoin.Conference.Web.Controllers
{
    using System.Web.Mvc;
    using Ucoin.Conference.Services;

    public class DefaultController : Controller
    {
        private readonly IConferenceViewService dao;

        public DefaultController(IConferenceViewService dao)
        {
            this.dao = dao;
        }

        public ActionResult Index()
        {
            return View(this.dao.GetPublishedConferences());
        }
    }
}

ConferenceManagement/Ucoin.Conference.Web/Views/Default/Index.cshtml
@model IEnumerable<Ucoin.Conference.Entities.ViewModel.ConferenceAlias>
@{
    ViewBag.Title = "Index";
}
<h1 class="page__head page__wrapper">List of conferences</h1>
<div class="page__content">
    <div class="page__wrapper content-main">
        <p>
            Go to the specific conference page:
        </p>
        <ul>
            @foreach (var conference in Model) {
                <li>@Html.ActionLink(conference.Name, "Display", "Conference", new { conferenceCode = conference.Code }, null)</li>
            }
        </ul>
    </div>
</div>